export const SITE_TITLE = "How Things Work";
export const SITE_DESCRIPTION =
  "A visual, interactive encyclopedia that explains how technologies work internally.";
export const SITE_URL = "https://howthingswork.aiwisdom.dev";

export type NavItem = {
  label: string;
  href: string;
  children?: NavItem[];
};

export const NAV_ITEMS: NavItem[] = [
  {
    label: "React",
    href: "/react",
    children: [
      { label: "Fiber Architecture", href: "/react/fiber-visualizer" },
      { label: "Virtual DOM & Diffing", href: "/react/virtual-dom" },
      { label: "Reconciliation", href: "/react/reconciliation" },
      { label: "Rendering Pipeline", href: "/react/rendering-pipeline" },
      { label: "Component Lifecycle", href: "/react/component-lifecycle" },
      { label: "Hooks Internals", href: "/react/hooks-visualizer" },
      { label: "useEffect Lifecycle", href: "/react/useeffect-lifecycle" },
      { label: "State & Batching", href: "/react/state-batching" },
      { label: "Memoization", href: "/react/memoization" },
      { label: "React.memo & Re-renders", href: "/react/react-memo" },
      { label: "Context API", href: "/react/context-api" },
      { label: "Event System", href: "/react/event-system" },
      { label: "Refs & DOM", href: "/react/refs-dom" },
      { label: "Keys & Lists", href: "/react/keys-lists" },
      { label: "Error Boundaries", href: "/react/error-boundaries" },
      { label: "Portals", href: "/react/portals" },
      { label: "Suspense & Lazy", href: "/react/suspense" },
      { label: "Concurrent Mode", href: "/react/concurrent-rendering" },
      { label: "Transitions", href: "/react/transitions" },
      { label: "Server Components", href: "/react/server-components" },
    ],
  },
  {
    label: "JavaScript",
    href: "/javascript",
    children: [
      { label: "Event Loop & Call Stack", href: "/javascript/event-loop" },
      { label: "Closures & Scope Chain", href: "/javascript/closures" },
      { label: "Prototypal Inheritance", href: "/javascript/prototypes" },
      { label: "Promises & Microtasks", href: "/javascript/promises" },
      { label: "Async/Await Internals", href: "/javascript/async-await" },
      { label: "Garbage Collection (V8)", href: "/javascript/garbage-collection" },
      { label: "Module System", href: "/javascript/modules" },
      { label: "this Binding Rules", href: "/javascript/this-binding" },
      { label: "Web APIs & Runtime", href: "/javascript/web-apis" },
      { label: "Memory Leaks", href: "/javascript/memory-leaks" },
    ],
  },
  {
    label: "C# / CLR",
    href: "/csharp-clr",
    children: [
      { label: "CLR Architecture", href: "/csharp-clr/clr-architecture" },
      { label: "JIT Compilation", href: "/csharp-clr/jit-visualizer" },
      { label: "Garbage Collector", href: "/csharp-clr/gc-visualizer" },
      { label: "Value vs Reference Types", href: "/csharp-clr/value-reference-types" },
      { label: "async/await State Machine", href: "/csharp-clr/async-state-machine" },
      { label: "LINQ Deferred Execution", href: "/csharp-clr/linq-execution" },
      { label: "Delegates & Events", href: "/csharp-clr/delegates-events" },
      { label: "Generics & Reification", href: "/csharp-clr/generics" },
      { label: "DI Container", href: "/csharp-clr/dependency-injection" },
      { label: "Reflection & Metadata", href: "/csharp-clr/reflection" },
    ],
  },
  {
    label: "ASP.NET Core",
    href: "/aspnet-core",
    children: [
      { label: "Middleware Pipeline", href: "/aspnet-core/middleware" },
      { label: "Routing & Endpoints", href: "/aspnet-core/routing" },
      { label: "Dependency Injection", href: "/aspnet-core/dependency-injection" },
      { label: "Authentication & Auth", href: "/aspnet-core/authentication" },
      { label: "Model Binding", href: "/aspnet-core/model-binding" },
      { label: "Filters", href: "/aspnet-core/filters" },
      { label: "Configuration", href: "/aspnet-core/configuration" },
      { label: "Logging & Diagnostics", href: "/aspnet-core/logging" },
      { label: "API Versioning", href: "/aspnet-core/api-versioning" },
      { label: "Error Handling", href: "/aspnet-core/error-handling" },
    ],
  },
  {
    label: "Entity Framework",
    href: "/entity-framework",
    children: [
      { label: "DbContext & Change Tracker", href: "/entity-framework/dbcontext" },
      { label: "Query Pipeline", href: "/entity-framework/query-pipeline" },
      { label: "Migrations", href: "/entity-framework/migrations" },
      { label: "Loading Strategies", href: "/entity-framework/loading-strategies" },
      { label: "Relationships", href: "/entity-framework/relationships" },
      { label: "Query Performance", href: "/entity-framework/query-performance" },
      { label: "Concurrency", href: "/entity-framework/concurrency" },
      { label: "Raw SQL", href: "/entity-framework/raw-sql" },
    ],
  },
  {
    label: "Azure Cloud",
    href: "/azure",
    children: [
      { label: "Azure Functions", href: "/azure/functions" },
      { label: "App Service", href: "/azure/app-service" },
      { label: "Entra ID (Azure AD)", href: "/azure/entra-id" },
      { label: "Service Bus", href: "/azure/service-bus" },
      { label: "Cosmos DB", href: "/azure/cosmos-db" },
      { label: "Blob Storage", href: "/azure/blob-storage" },
      { label: "API Management", href: "/azure/api-management" },
      { label: "App Insights", href: "/azure/app-insights" },
      { label: "Key Vault", href: "/azure/key-vault" },
      { label: "DevOps Pipelines", href: "/azure/devops-pipelines" },
    ],
  },
  {
    label: "Architecture",
    href: "/architecture",
    children: [
      { label: "SOLID Principles", href: "/architecture/solid" },
      { label: "OOP Pillars", href: "/architecture/oop" },
      { label: "Clean Architecture", href: "/architecture/clean-architecture" },
      { label: "Repository Pattern", href: "/architecture/repository-pattern" },
      { label: "CQRS & Event Sourcing", href: "/architecture/cqrs" },
      { label: "Mediator Pattern", href: "/architecture/mediator" },
      { label: "Strategy, Factory, Observer", href: "/architecture/design-patterns" },
      { label: "Decorator & Chain", href: "/architecture/decorator-chain" },
      { label: "Domain-Driven Design", href: "/architecture/ddd" },
      { label: "Anti-Patterns", href: "/architecture/anti-patterns" },
    ],
  },
  {
    label: "Microservices",
    href: "/microservices",
    children: [
      { label: "Monolith vs Micro", href: "/microservices/monolith-vs-micro" },
      { label: "API Gateway", href: "/microservices/api-gateway" },
      { label: "Service Discovery", href: "/microservices/service-discovery" },
      { label: "Communication", href: "/microservices/communication" },
      { label: "Circuit Breaker", href: "/microservices/circuit-breaker" },
      { label: "Saga Pattern", href: "/microservices/saga" },
      { label: "Event-Driven", href: "/microservices/event-driven" },
      { label: "Containers & K8s", href: "/microservices/containers" },
      { label: "Observability", href: "/microservices/observability" },
      { label: "Data Management", href: "/microservices/data-management" },
    ],
  },
  {
    label: "Testing",
    href: "/testing",
    children: [
      { label: "Unit Testing Basics", href: "/testing/unit-testing" },
      { label: "xUnit & NUnit", href: "/testing/xunit-nunit" },
      { label: "Jest & RTL", href: "/testing/jest-rtl" },
      { label: "Mocking", href: "/testing/mocking" },
      { label: "Integration Tests", href: "/testing/integration" },
      { label: "Playwright E2E", href: "/testing/playwright" },
      { label: "TDD", href: "/testing/tdd" },
      { label: "Code Coverage", href: "/testing/coverage" },
      { label: "Contract Testing", href: "/testing/contract-testing" },
      { label: "Performance Testing", href: "/testing/performance" },
    ],
  },
  {
    label: "System Design",
    href: "/system-design",
    children: [
      { label: "Scalability", href: "/system-design/scalability" },
      { label: "Load Balancers", href: "/system-design/load-balancers" },
      { label: "Caching", href: "/system-design/caching" },
      { label: "Sharding & Replication", href: "/system-design/sharding" },
      { label: "Message Queues", href: "/system-design/message-queues" },
      { label: "Rate Limiting", href: "/system-design/rate-limiting" },
      { label: "CDN & Edge", href: "/system-design/cdn" },
      { label: "Auth at Scale", href: "/system-design/auth-at-scale" },
      { label: "Database Indexing", href: "/system-design/indexing" },
      { label: "Designing for Failure", href: "/system-design/failure-design" },
    ],
  },
  {
    label: "AI & ML",
    href: "/ai-ml",
    children: [
      { label: "Neural Networks", href: "/ai-ml/neural-networks" },
      { label: "Embeddings & Vectors", href: "/ai-ml/embeddings" },
      { label: "Transformers", href: "/ai-ml/transformers" },
      { label: "RAG Architecture", href: "/ai-ml/rag" },
      { label: "Fine-Tuning", href: "/ai-ml/fine-tuning" },
      { label: "AI Agents", href: "/ai-ml/agents" },
      { label: "Tokenization", href: "/ai-ml/tokenization" },
      { label: "Model Serving", href: "/ai-ml/model-serving" },
      { label: "LangChain / Semantic Kernel", href: "/ai-ml/orchestration" },
      { label: "Responsible AI", href: "/ai-ml/responsible-ai" },
    ],
  },
];
