"use client";

import { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Button from "@/app/_ui/Button";
import Panel from "@/app/_ui/Panel";

type Mode = "reflection" | "sourcegen";

interface PropertyInfo {
  name: string;
  typeName: string;
  attributes: string[];
  canRead: boolean;
  canWrite: boolean;
}

interface MethodInfo {
  name: string;
  returnType: string;
  parameters: string;
  isPublic: boolean;
  isAsync: boolean;
}

interface TypeData {
  fullName: string;
  baseType: string;
  interfaces: string[];
  isClass: boolean;
  properties: PropertyInfo[];
  methods: MethodInfo[];
  attributes: string[];
  sourceGenCode: string;
}

const SAMPLE_TYPES: Record<string, TypeData> = {
  Order: {
    fullName: "MyApp.Domain.Order",
    baseType: "System.Object",
    interfaces: ["IEntity", "IAuditable"],
    isClass: true,
    attributes: ["[Table(\"orders\")]", "[JsonSerializable]"],
    properties: [
      { name: "Id", typeName: "Guid", attributes: ["[Key]"], canRead: true, canWrite: false },
      { name: "CustomerId", typeName: "Guid", attributes: ["[Required]", "[ForeignKey(\"Customer\")]"], canRead: true, canWrite: true },
      { name: "TotalAmount", typeName: "decimal", attributes: ["[Column(TypeName = \"decimal(18,2)\")]"], canRead: true, canWrite: true },
      { name: "Status", typeName: "OrderStatus", attributes: ["[JsonConverter(typeof(JsonStringEnumConverter))]"], canRead: true, canWrite: true },
      { name: "CreatedAt", typeName: "DateTimeOffset", attributes: ["[DatabaseGenerated(DatabaseGeneratedOption.Identity)]"], canRead: true, canWrite: false },
    ],
    methods: [
      { name: "PlaceAsync", returnType: "Task<OrderResult>", parameters: "CancellationToken ct", isPublic: true, isAsync: true },
      { name: "Cancel", returnType: "void", parameters: "string reason", isPublic: true, isAsync: false },
      { name: "CalculateTax", returnType: "decimal", parameters: "", isPublic: false, isAsync: false },
      { name: "GetHashCode", returnType: "int", parameters: "", isPublic: true, isAsync: false },
    ],
    sourceGenCode: `// Generated by [JsonSerializable] source generator
// Zero reflection at runtime — code emitted at compile time

[JsonSerializable(typeof(Order))]
[JsonSerializable(typeof(List<Order>))]
internal partial class AppJsonContext : JsonSerializerContext { }

// Equivalent of what the generator emits:
internal static class OrderJsonSerializer
{
    // Metadata tables — no Type.GetProperties() at runtime
    private static readonly JsonPropertyInfo[] s_properties = new[]
    {
        new JsonPropertyInfo<Order, Guid>("Id",   o => o.Id,   null),
        new JsonPropertyInfo<Order, Guid>("customerId", o => o.CustomerId, (o,v) => o.CustomerId = v),
        // ... all properties generated at compile time
    };

    public static void Serialize(Utf8JsonWriter writer, Order value)
    {
        writer.WriteStartObject();
        writer.WriteString("id"s, value.Id);           // direct property access
        writer.WriteString("customerId", value.CustomerId); // no boxing, no reflection
        writer.WriteNumber("totalAmount", value.TotalAmount);
        writer.WriteEndObject();
    }
}

// Usage — same API, no reflection:
var json = JsonSerializer.Serialize(order, AppJsonContext.Default.Order);`,
  },
  UserRepository: {
    fullName: "MyApp.Data.UserRepository",
    baseType: "RepositoryBase<User>",
    interfaces: ["IUserRepository", "IDisposable"],
    isClass: true,
    attributes: ["[RegisterScoped]", "[GeneratedCode(\"DI.SourceGen\", \"1.0\")]"],
    properties: [
      { name: "DbContext", typeName: "AppDbContext", attributes: ["[Inject]"], canRead: true, canWrite: false },
      { name: "Logger", typeName: "ILogger<UserRepository>", attributes: ["[Inject]"], canRead: true, canWrite: false },
    ],
    methods: [
      { name: "FindByIdAsync", returnType: "Task<User?>", parameters: "Guid id, CancellationToken ct", isPublic: true, isAsync: true },
      { name: "FindByEmailAsync", returnType: "Task<User?>", parameters: "string email, CancellationToken ct", isPublic: true, isAsync: true },
      { name: "ExistsAsync", returnType: "Task<bool>", parameters: "Guid id, CancellationToken ct", isPublic: true, isAsync: true },
      { name: "Dispose", returnType: "void", parameters: "", isPublic: true, isAsync: false },
    ],
    sourceGenCode: `// IIncrementalGenerator — runs at compile time, emits DI registrations
// No runtime reflection needed to scan assemblies for [RegisterScoped]

[Generator]
public class DependencyInjectionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext ctx)
    {
        var provider = ctx.SyntaxProvider
            .ForAttributeWithMetadataName(
                "RegisterScopedAttribute",
                predicate: (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Collect();

        ctx.RegisterSourceOutput(provider, (spc, types) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("public static partial class GeneratedRegistrations {");
            sb.AppendLine("  public static void AddGeneratedServices(this IServiceCollection services) {");
            foreach (var type in types)
                sb.AppendLine($"    services.AddScoped<I{type.Name}, {type.Name}>();");
            sb.AppendLine("  }");
            sb.AppendLine("}");
            spc.AddSource("GeneratedRegistrations.g.cs", sb.ToString());
        });
    }
}

// Generated output — deterministic, trimmer-safe:
// GeneratedRegistrations.g.cs
public static partial class GeneratedRegistrations {
  public static void AddGeneratedServices(this IServiceCollection services) {
    services.AddScoped<IUserRepository, UserRepository>();
  }
}`,
  },
};

const TYPE_NAMES = Object.keys(SAMPLE_TYPES);

export default function ReflectionVisualizer() {
  const [selectedType, setSelectedType] = useState<string | null>(null);
  const [mode, setMode] = useState<Mode>("reflection");
  const [reflecting, setReflecting] = useState(false);
  const [typeData, setTypeData] = useState<TypeData | null>(null);
  const [expandedProp, setExpandedProp] = useState<string | null>(null);

  const reflect = useCallback(
    async (typeName: string) => {
      if (reflecting) return;
      setReflecting(true);
      setTypeData(null);
      setSelectedType(typeName);
      setExpandedProp(null);

      // Simulate reflection overhead
      await new Promise((r) => setTimeout(r, 600));
      setTypeData(SAMPLE_TYPES[typeName]);
      setReflecting(false);
    },
    [reflecting]
  );

  const data = typeData;

  return (
    <div className="space-y-4">
      {/* Type selector + mode toggle */}
      <div className="flex flex-wrap gap-4 items-center">
        <div>
          <p className="text-[11px] font-mono uppercase text-text-secondary mb-2">
            Select a type to inspect
          </p>
          <div className="flex gap-2">
            {TYPE_NAMES.map((name) => (
              <button
                key={name}
                onClick={() => reflect(name)}
                disabled={reflecting}
                className={`font-mono text-sm px-4 py-2 rounded-lg border transition-all duration-200 ${
                  selectedType === name
                    ? "border-accent bg-accent/15 text-accent"
                    : "border-border bg-elevated text-text-secondary hover:border-accent/40"
                }`}
              >
                {name}
              </button>
            ))}
          </div>
        </div>

        {data && (
          <div>
            <p className="text-[11px] font-mono uppercase text-text-secondary mb-2">Mode</p>
            <div className="flex rounded-lg border border-border overflow-hidden">
              <button
                onClick={() => setMode("reflection")}
                className={`px-4 py-2 text-xs font-mono transition-all ${
                  mode === "reflection"
                    ? "bg-accent/20 text-accent border-r border-accent/30"
                    : "bg-elevated text-text-secondary hover:text-text-primary border-r border-border"
                }`}
              >
                Runtime Reflection
              </button>
              <button
                onClick={() => setMode("sourcegen")}
                className={`px-4 py-2 text-xs font-mono transition-all ${
                  mode === "sourcegen"
                    ? "bg-cyan-500/20 text-cyan-400"
                    : "bg-elevated text-text-secondary hover:text-text-primary"
                }`}
              >
                Source Generator (.NET 7+)
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Reflecting indicator */}
      <AnimatePresence>
        {reflecting && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="flex items-center gap-3 p-4 border border-border rounded-lg bg-elevated"
          >
            <div className="w-4 h-4 border-2 border-accent border-t-transparent rounded-full animate-spin" />
            <span className="font-mono text-xs text-accent">
              Assembly.GetTypes() → Type.GetProperties(BindingFlags.Public | BindingFlags.Instance) → loading metadata…
            </span>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main content */}
      <AnimatePresence mode="wait">
        {data && !reflecting && (
          <motion.div
            key={`${selectedType}-${mode}`}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="space-y-4"
          >
            {mode === "reflection" ? (
              <>
                {/* Type header */}
                <Panel title="Type" accentColor="#A855F7">
                  <div className="space-y-2">
                    <div className="flex items-center gap-3 flex-wrap">
                      <span className="font-mono text-sm text-accent font-bold">{data.fullName}</span>
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded border border-border text-text-secondary">
                        {data.isClass ? "class" : "struct"}
                      </span>
                    </div>
                    <div className="grid grid-cols-2 gap-3 text-[11px] font-mono">
                      <div>
                        <span className="text-text-secondary">BaseType: </span>
                        <span className="text-blue-400">{data.baseType}</span>
                      </div>
                      <div>
                        <span className="text-text-secondary">Interfaces: </span>
                        <span className="text-emerald-400">{data.interfaces.join(", ")}</span>
                      </div>
                    </div>
                    <div className="flex gap-2 flex-wrap">
                      {data.attributes.map((attr) => (
                        <span
                          key={attr}
                          className="text-[10px] font-mono px-2 py-0.5 rounded border border-amber-500/40 bg-amber-500/10 text-amber-300"
                        >
                          {attr}
                        </span>
                      ))}
                    </div>
                    <div className="text-[10px] font-mono text-text-secondary bg-[#0D0D0D] rounded-lg p-2 border border-border">
                      {`Type t = Type.GetType("${data.fullName}, MyApp");`}
                      <br />
                      {`// or: typeof(${selectedType})`}
                    </div>
                  </div>
                </Panel>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                  {/* Properties */}
                  <Panel title={`Properties (${data.properties.length})`} accentColor="#06B6D4">
                    <div className="space-y-1.5">
                      {data.properties.map((prop) => (
                        <div key={prop.name}>
                          <button
                            className="w-full text-left rounded-lg border border-border bg-[#0D0D0D] p-2.5 hover:border-accent/30 transition-all"
                            onClick={() =>
                              setExpandedProp(expandedProp === prop.name ? null : prop.name)
                            }
                          >
                            <div className="flex items-center justify-between">
                              <div className="flex items-center gap-2">
                                <span className="text-[10px] font-mono text-cyan-400">{prop.typeName}</span>
                                <span className="text-xs font-mono text-text-primary font-semibold">{prop.name}</span>
                              </div>
                              <div className="flex gap-1">
                                {prop.canRead && (
                                  <span className="text-[9px] px-1.5 py-0.5 rounded border border-green-500/30 bg-green-500/10 text-green-400 font-mono">get</span>
                                )}
                                {prop.canWrite && (
                                  <span className="text-[9px] px-1.5 py-0.5 rounded border border-blue-500/30 bg-blue-500/10 text-blue-400 font-mono">set</span>
                                )}
                              </div>
                            </div>
                          </button>
                          <AnimatePresence>
                            {expandedProp === prop.name && (
                              <motion.div
                                initial={{ height: 0, opacity: 0 }}
                                animate={{ height: "auto", opacity: 1 }}
                                exit={{ height: 0, opacity: 0 }}
                                className="overflow-hidden"
                              >
                                <div className="flex flex-wrap gap-1.5 p-2 border border-t-0 border-border rounded-b-lg bg-elevated">
                                  {prop.attributes.map((attr) => (
                                    <span
                                      key={attr}
                                      className="text-[10px] font-mono px-2 py-0.5 rounded border border-amber-500/40 bg-amber-500/10 text-amber-300"
                                    >
                                      {attr}
                                    </span>
                                  ))}
                                  <span className="text-[10px] font-mono text-text-secondary">
                                    PropertyInfo.GetCustomAttributes(true)
                                  </span>
                                </div>
                              </motion.div>
                            )}
                          </AnimatePresence>
                        </div>
                      ))}
                    </div>
                  </Panel>

                  {/* Methods */}
                  <Panel title={`Methods (${data.methods.length})`} accentColor="#10B981">
                    <div className="space-y-1.5">
                      {data.methods.map((method) => (
                        <div
                          key={method.name}
                          className="rounded-lg border border-border bg-[#0D0D0D] p-2.5"
                        >
                          <div className="flex items-start justify-between gap-2">
                            <div>
                              <div className="flex items-center gap-1.5 flex-wrap">
                                {method.isAsync && (
                                  <span className="text-[9px] font-mono text-purple-400 border border-purple-500/30 bg-purple-500/10 px-1.5 py-0.5 rounded">
                                    async
                                  </span>
                                )}
                                <span className="text-[10px] font-mono text-cyan-400">{method.returnType}</span>
                                <span className="text-xs font-mono text-text-primary font-semibold">{method.name}</span>
                              </div>
                              <p className="text-[10px] font-mono text-text-secondary mt-0.5">
                                ({method.parameters || "void"})
                              </p>
                            </div>
                            <span
                              className={`text-[9px] font-mono px-1.5 py-0.5 rounded border flex-shrink-0 ${
                                method.isPublic
                                  ? "border-green-500/30 bg-green-500/10 text-green-400"
                                  : "border-border text-text-secondary"
                              }`}
                            >
                              {method.isPublic ? "public" : "private"}
                            </span>
                          </div>
                        </div>
                      ))}
                    </div>

                    <div className="mt-3 bg-[#0D0D0D] rounded-lg p-2 border border-red-500/20">
                      <p className="text-[10px] font-mono text-red-400">
                        ⚠ BindingFlags.NonPublic | BindingFlags.Instance also returns private methods — reflection bypasses access modifiers
                      </p>
                    </div>
                  </Panel>
                </div>
              </>
            ) : (
              /* Source Generator mode */
              <Panel title="Source Generator — Compile-Time Equivalent" accentColor="#06B6D4">
                <div className="space-y-3">
                  <div className="flex items-center gap-2 p-3 border border-cyan-500/30 bg-cyan-500/10 rounded-lg">
                    <span className="text-[11px] font-mono text-cyan-300 leading-relaxed">
                      Instead of calling Type.GetProperties() at runtime, an IIncrementalGenerator reads the Roslyn syntax tree at compile time and emits equivalent C# code. Zero runtime cost, AOT-safe, trimmer-safe.
                    </span>
                  </div>
                  <pre className="font-mono text-[11px] text-text-secondary bg-[#0D0D0D] border border-border rounded-lg p-4 overflow-x-auto whitespace-pre leading-relaxed max-h-[420px] overflow-y-auto">
                    {data.sourceGenCode}
                  </pre>
                  <div className="grid grid-cols-2 gap-3 text-[11px] font-mono">
                    <div className="border border-red-500/30 bg-red-500/5 rounded-lg p-3">
                      <p className="text-red-400 font-semibold mb-1">Runtime Reflection</p>
                      <p className="text-text-secondary">Type.GetProperties() — heap allocations</p>
                      <p className="text-text-secondary">PropertyInfo[] — metadata loading</p>
                      <p className="text-text-secondary">Reflection.Emit — IL generation at runtime</p>
                      <p className="text-red-400 mt-1">Broken by NativeAOT linker trimming</p>
                    </div>
                    <div className="border border-cyan-500/30 bg-cyan-500/5 rounded-lg p-3">
                      <p className="text-cyan-400 font-semibold mb-1">Source Generator</p>
                      <p className="text-text-secondary">Code generated at compile time</p>
                      <p className="text-text-secondary">Direct property access — no boxing</p>
                      <p className="text-text-secondary">Visible in IDE — fully debuggable</p>
                      <p className="text-cyan-400 mt-1">NativeAOT and trimming safe</p>
                    </div>
                  </div>
                </div>
              </Panel>
            )}
          </motion.div>
        )}
      </AnimatePresence>

      {!data && !reflecting && (
        <div className="border border-border rounded-xl p-8 text-center">
          <p className="text-text-secondary font-mono text-sm">
            Select a type above to inspect it with reflection
          </p>
          <p className="text-text-secondary font-mono text-xs mt-1">
            Click properties to expand attributes • Toggle to Source Generator mode to see compile-time alternative
          </p>
        </div>
      )}
    </div>
  );
}
